project:
  type: website
  output-dir: docs
  
website: 
  title: "Anum Damani"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: About
      - projects.qmd
      - coursework.qmd
      - tools.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
